# Generated by Django 5.2.5 on 2025-09-21 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='area',
            field=models.CharField(default='未設定', max_length=50),
            preserve_default=False,
        ),
    ]
