# Generated by Django 5.2.5 on 2025-09-24 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_alter_visit_feeling'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='feeling',
            field=models.CharField(blank=True, choices=[('again', 'また行きたい'), ('recommend', 'おすすめしたい'), ('no', 'もう行かない')], max_length=20, null=True),
        ),
    ]
