# Generated by Django 5.2.5 on 2025-09-24 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_alter_visit_feeling'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='status',
            field=models.CharField(choices=[('want', '気になる'), ('went', '行った')], default='want', max_length=10, verbose_name='ステータス'),
        ),
    ]
