# Generated by Django 5.2.5 on 2025-09-27 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0005_restaurant_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='category',
            field=models.CharField(choices=[('genre', 'ジャンル'), ('area', 'エリア'), ('scene', 'シーン'), ('group', 'グループ'), ('custom', 'カスタム')], default='custom', max_length=20),
        ),
    ]
