# Generated by Django 5.2.5 on 2025-10-06 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0006_tag_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='instagram_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='tiktok_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
