# Generated by Django 5.2.5 on 2025-10-06 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0007_restaurant_instagram_url_restaurant_tiktok_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='instagram_url',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='tiktok_url',
        ),
    ]
