# Generated by Django 5.2.5 on 2025-11-12 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0013_alter_restaurant_holiday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='holiday',
            field=models.CharField(blank=True, choices=[('月', '月曜日'), ('火', '火曜日'), ('水', '水曜日'), ('木', '木曜日'), ('金', '金曜日'), ('土', '土曜日'), ('日', '日曜日'), ('祝日', '祝日'), ('年中無休', '年中無休'), ('不定休', '不定休')], max_length=50, null=True, verbose_name='休業日'),
        ),
    ]
