# Generated by Django 5.2.5 on 2025-11-12 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0014_alter_restaurant_holiday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='holiday',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='休業日'),
        ),
    ]
