# Generated by Django 5.2.5 on 2025-11-18 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0015_alter_restaurant_holiday'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuggestWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_type', models.CharField(choices=[('area', 'Area'), ('genre', 'Genre'), ('group', 'Group'), ('scene', 'Scene'), ('tag', 'Tag')], max_length=20)),
                ('word', models.CharField(max_length=50)),
            ],
            options={
                'unique_together': {('word_type', 'word')},
            },
        ),
    ]
